/**
 * SPECS PAGE
 *
 * The documentation layer: every component, primitive, and pattern in
 * Scorp DS has a spec file in the repo (docs/specs/*.md), generated by
 * /update-spec and mirrored to Notion by the sync skills. This page shows
 * what a spec looks like (the Link spec, the most complete one today) and
 * indexes all 32 with links to their Notion mirrors.
 *
 * Page structure follows the Essay/Case Study editorial layout: headline
 * and prose via CaseStudyBlocks, with DS Table and ListRow for the spec
 * anatomy and index (content the block vocabulary doesn't cover).
 */

import { CaseStudyBlocks, type CaseStudyBlock } from "@/components/ui/CaseStudy";
import { Link } from "@/components/ui/Link";
import { ListRow } from "@/components/ui/ListRow";
import { TuiIcon } from "@/components/ui/TuiIcon";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/Table";

const NOTION_HUB_URL = "https://www.notion.so/3e29a6335da181be8280c9bfc8730512";
const SPECS_SOURCE_URL =
  "https://github.com/sachahurley/scorp-ds/tree/main/docs/specs";

const notionUrl = (id: string) => `https://www.notion.so/${id}`;

// The index: every spec file and its Notion mirror, grouped as in the repo
const SPEC_GROUPS: {
  title: string;
  specs: { name: string; notionId: string }[];
}[] = [
  {
    title: "Components and primitives",
    specs: [
      { name: "Alert", notionId: "3e29a6335da181c78e1dd773d378eb53" },
      { name: "Avatar", notionId: "3e29a6335da1819791bce0bd15ee5694" },
      { name: "Badge", notionId: "3e29a6335da18119bd34e4e82a6cf5fa" },
      { name: "BottomSheet", notionId: "3e29a6335da181a09994f535db5144ca" },
      { name: "Button", notionId: "3e29a6335da1810385a1d3bbdb3c4478" },
      { name: "Card", notionId: "3e29a6335da1813c9d98daa13f50a98e" },
      { name: "CaseStudy", notionId: "3e29a6335da1811682f0d22daabc5208" },
      { name: "Checkbox", notionId: "3e29a6335da181938b24ed35c1c81125" },
      { name: "Divider", notionId: "3e29a6335da18195bfe1d61f6b404c40" },
      { name: "Dropdown", notionId: "3e29a6335da181968e82f0f6729a938b" },
      { name: "Input", notionId: "3e29a6335da181168df8d05a1c32c590" },
      { name: "Link", notionId: "3e29a6335da181e585e1d3e6bf99882e" },
      { name: "ListRow", notionId: "3e29a6335da1810c9226d7f13c1dcaa0" },
      { name: "Modal", notionId: "3e29a6335da181adaa24c84f7e463950" },
      { name: "Radio", notionId: "3e29a6335da1814ab65fe51965913674" },
      { name: "Select", notionId: "3e29a6335da181f987e6eec44dca244d" },
      { name: "Stack", notionId: "3e29a6335da181feae9efc7c3f2fda43" },
      { name: "Switch", notionId: "3e29a6335da181a9bc83f883c105e7dd" },
      { name: "Table", notionId: "3e29a6335da181e7b04dee8b6be80ed4" },
      { name: "Tabs", notionId: "3e29a6335da1812e8df5cfc566d6277a" },
      { name: "Textarea", notionId: "3e29a6335da181859ab7cf9a357aa9e7" },
      { name: "ThemeToggle", notionId: "3e29a6335da181fe9d9fdb9b223a499b" },
      { name: "Toast", notionId: "3e29a6335da181c1b3c9eab225b11694" },
      { name: "Tooltip", notionId: "3e29a6335da18160bc35fc5d700fe47c" },
      { name: "TuiIcon", notionId: "3e29a6335da1819c8006f82421bc0acc" },
    ],
  },
  {
    title: "Patterns",
    specs: [
      { name: "Dense list row", notionId: "3e29a6335da1812daae9c9b9dff08bc3" },
      { name: "Music player", notionId: "3e29a6335da181539511c66130c83240" },
      { name: "Settings panel", notionId: "3e29a6335da18154b397f15127c41c97" },
      { name: "TUI Unicode & ASCII art", notionId: "3e29a6335da1815197bfd74cde6df7a8" },
      { name: "Workbench split", notionId: "3e29a6335da181a093d3ef95011abe37" },
    ],
  },
  {
    title: "Foundation and meta",
    specs: [
      { name: "token-parser", notionId: "3e29a6335da181b4b779c8459cc0957c" },
      { name: "Spec Changelog", notionId: "3e29a6335da1813e97fac3992e2a3cac" },
    ],
  },
];

// Page intro and section headings, in the editorial block vocabulary
const INTRO: CaseStudyBlock[] = [
  {
    type: "headline",
    kicker: "Specs",
    title: "Every Part Has a Paper Trail",
  },
  {
    type: "prose",
    text: "Every component, primitive, and pattern in Scorp DS has a spec: a markdown file in the repo covering its status, intent, anatomy, token usage, states, and accessibility contract. Specs are generated and updated by the /update-spec skill, which preserves human-written sections across regenerations, and the sync skills mirror each one to a Notion page. The markdown in the repo is the source of truth; Notion is the readable mirror.",
  },
  {
    type: "headline",
    title: "Anatomy of a Spec",
    text: "The Link spec is the most complete one today. These are its key sections, abbreviated.",
  },
];

const INDEX_HEADER: CaseStudyBlock[] = [
  {
    type: "headline",
    title: "All Specs",
    text: "The full index: 25 components and primitives, 5 patterns, the token parser, and the spec changelog. Each row opens that spec's Notion mirror.",
  },
];

// Text tones matching the CaseStudyBlocks body treatment
const BODY_TEXT = "text-sm font-mono text-secondary-800 dark:text-secondary-500";
const HEADING_TEXT = "text-sm font-mono text-[var(--text-primary)]";

/** One labeled sub-section of the example spec */
function SpecSection({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-8">
      <h3 className={`${HEADING_TEXT} mb-3`}>{title}</h3>
      {children}
    </section>
  );
}

export default function Specs() {
  return (
    <div className="container mx-auto px-5 lg:px-10 pt-5 lg:pt-10 pb-5 lg:pb-20">
      {/* Reading column: same editorial width as Essay and Case Study */}
      <div className="mx-auto max-w-2xl [container-type:inline-size]">
        <CaseStudyBlocks blocks={INTRO} />

        {/* EXAMPLE SPEC: curated sections of docs/specs/Link.md */}
        <div className="mt-8">
          <SpecSection title="Status">
            <Table density="compact">
              <TableBody>
                {(
                  [
                    ["Widget", "ScorpLink"],
                    ["Layer", "component"],
                    ["Category", "Navigation"],
                    ["Story", "Components/Navigation/Link"],
                    ["Version", "v1"],
                    ["Status", "draft"],
                    ["Last synced", "2026-09-20"],
                  ] as const
                ).map(([field, value]) => (
                  <TableRow key={field}>
                    <TableCell className="text-secondary-700 dark:text-secondary-600">
                      {field}
                    </TableCell>
                    <TableCell>{value}</TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </SpecSection>

          <SpecSection title="Intent">
            <p className={`${BODY_TEXT} leading-6 mb-3`}>
              Inline text link for navigation. Always renders a real anchor (or
              a custom router link), never a button: links navigate, Button
              acts. Two variants: inline (persistent underline, the safe
              treatment inside body text) and quiet (underline on hover and
              focus, for nav lists where position already signals the link).
            </p>
            <p className={`${BODY_TEXT} leading-6`}>
              There is deliberately no disabled state: a link without a
              destination is just text, so render text.
            </p>
          </SpecSection>

          <SpecSection title="Properties">
            <Table density="compact">
              <TableHeader>
                <TableRow>
                  <TableHead>Property</TableHead>
                  <TableHead>Type</TableHead>
                  <TableHead>Default</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {(
                  [
                    ["variant", '"inline" | "quiet"', '"inline"'],
                    ["external", "boolean", "false"],
                    ["href", "string", "-"],
                    ["as / asProps", "ElementType / props", "-"],
                    ["children", "ReactNode", "required"],
                  ] as const
                ).map(([prop, type, def]) => (
                  <TableRow key={prop}>
                    <TableCell>{prop}</TableCell>
                    <TableCell className="text-secondary-700 dark:text-secondary-600">
                      {type}
                    </TableCell>
                    <TableCell className="text-secondary-700 dark:text-secondary-600">
                      {def}
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </SpecSection>

          <SpecSection title="Token Map">
            <Table density="compact">
              <TableHeader>
                <TableRow>
                  <TableHead>Token</TableHead>
                  <TableHead>Usage</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {(
                  [
                    ["accent", "Resting text color (the documented links role)"],
                    ["text.link-hover", "Hover color: darkens in light, brightens in dark"],
                    ["focus.ring.primary", "Outside outline on focus-visible"],
                    ["duration.fast", "Hover color transition (150ms)"],
                  ] as const
                ).map(([token, usage]) => (
                  <TableRow key={token}>
                    <TableCell>{token}</TableCell>
                    <TableCell className="text-secondary-700 dark:text-secondary-600">
                      {usage}
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </SpecSection>

          <SpecSection title="Do / Don't">
            <ul className={`${BODY_TEXT} leading-6 list-none space-y-2`}>
              <li>DO use Link for navigation inside prose and for nav lists.</li>
              <li>DO use as/asProps for router links instead of wrapping.</li>
              <li>DON'T use Link for actions (open modal, submit); that's Button.</li>
              <li>DON'T disable a link; drop the wrapper and render text.</li>
            </ul>
          </SpecSection>

          <p className={`${BODY_TEXT} mb-4`}>
            The full spec also covers anatomy, states, Storybook coverage,
            dependencies, accessibility, and known gaps.{" "}
            <Link
              href={notionUrl("3e29a6335da181e585e1d3e6bf99882e")}
              external
              className="text-sm"
            >
              Read the complete Link spec
            </Link>
            .
          </p>
        </div>

        {/* THE INDEX (top margin: a fresh block array starts without the
            inter-section spacing the renderer adds between sibling blocks) */}
        <div className="mt-16">
          <CaseStudyBlocks blocks={INDEX_HEADER} />
        </div>
        <div className="mt-6">
          {SPEC_GROUPS.map((group) => (
            <section key={group.title} className="mb-8">
              <h3 className={`${HEADING_TEXT} mb-3`}>{group.title}</h3>
              <div className="flex flex-col gap-1">
                {group.specs.map((spec) => (
                  <ListRow
                    key={spec.name}
                    title={spec.name}
                    titleSuffix={<TuiIcon name="ExternalLink" size="3" className="ml-1" />}
                    href={notionUrl(spec.notionId)}
                    target="_blank"
                    rel="noopener noreferrer"
                  />
                ))}
              </div>
            </section>
          ))}
        </div>

        {/* Outbound links, matching the Home footer treatment */}
        <div className="mt-10 flex flex-wrap gap-x-6 gap-y-2">
          <Link href={NOTION_HUB_URL} external className="text-sm">
            Notion specs hub
          </Link>
          <Link href={SPECS_SOURCE_URL} external className="text-sm">
            Spec sources on GitHub
          </Link>
        </div>
      </div>
    </div>
  );
}
