# GitHub Actions workflow for automatic deployment to GitHub Pages
# Runs whenever code is pushed to the main branch
# Builds the project and deploys to gh-pages branch

name: Deploy to GitHub Pages

on:
  # Trigger on push to main branch
  push:
    branches:
      - main
  
  # Allow manual triggering from Actions tab
  workflow_dispatch:

# Set permissions for GitHub token
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci
      
      # Step 4: Build the project
      - name: Build project
        run: npm run build
      
      # Step 5: Deploy to GitHub Pages
      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'

